name = "TommysRegistry"
uuid = "924364b3-aa26-4a4e-b826-36a413ad8f92"
repo = "https://github.com/thofma/Registry"

[packages]
7acfbe5b-c34a-4b87-9116-540863c2b2a3 = { name = "MagmaGroups", path = "M/MagmaGroups" }
928126d8-517c-4547-9366-53ef25125cdd = { name = "TestingSFC", path = "T/TestingSFC" }
bbc12448-813b-4029-aa6c-5ca2c038c8b3 = { name = "MagmaCall", path = "M/MagmaCall" }
