name = "TommysRegistry"
uuid = "924364b3-aa26-4a4e-b826-36a413ad8f92"
repo = "https://github.com/thofma/Registry"

[packages]
928126d8-517c-4547-9366-53ef25125cdd = { name = "TestingSFC", path = "T/TestingSFC" }
